# -*- coding: utf-8 -*-
"""【教材ソースコード】Lesson8: Language models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zdx_xyd492I5JOltElMw9_r8fTq2V49G

# Lesson8: LangChainの主要モジュール1【Model I/O】：Language models

## 事前準備

OpenAI APIキーの設定
"""

import os
from google.colab import userdata

os.environ["OPENAI_API_KEY"] = userdata.get("OPENAI_API_KEY")

"""各種パッケージのインストール"""

!pip install langchain==0.3.0 openai==1.47.0 langchain-community==0.3.0 langchain-openai==0.2.2 httpx==0.27.2

"""## 教材ソースコード

### Chat models

Lesson6で解説した、OpenAI APIにプロンプトを渡して回答を生成するコード
"""

from openai import OpenAI

client = OpenAI(api_key=os.environ["OPENAI_API_KEY"])

first_completion = client.chat.completions.create(
   model="gpt-4o-mini",
   messages=[
       {"role": "system", "content": "あなたは健康に関するアドバイザーです。安全なアドバイスを提供してください。"},
       {"role": "user", "content": "最近眠れないのですが、どうしたらいいですか？"}
   ],
   temperature=0.5
)

print(first_completion.choices[0].message.content)

"""ChatOpenAIクラスを使ったコード"""

from langchain_openai import ChatOpenAI
from langchain.schema import SystemMessage, HumanMessage

llm = ChatOpenAI(model_name="gpt-4o-mini", temperature=0)

messages = [
    SystemMessage(content="You are a helpful assistant."),
    HumanMessage(content="日本の首都を教えてください。"),
]

result = llm(messages)
print(result.content)

"""生成結果の確認"""

type(result)

print(result)