# -*- coding: utf-8 -*-
"""Chapter7:【提出課題: 解答用】5種類のMemory全ての回答結果を一覧化しよう

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18BgGqUgHZZ3LnqDwuTnrUtiQpO5yQTGV

# Lesson12: LangChainの主要モジュール2【Memory】
# Chapter7:【提出課題: 解答用】5種類のMemory全ての回答結果を一覧化しよう

事前準備を行った上で、提出課題に取り組みましょう。

**【提出方法】**  
Slackでメンターをメンションの上、当シート右上の「共有」からリンクをコピーし、提出してください。

## 事前準備

OpenAI APIキーの設定
"""

import os
from google.colab import userdata

os.environ["OPENAI_API_KEY"] = userdata.get("OPENAI_API_KEY")

"""各種パッケージのインストール"""

!pip install langchain==0.3.0 openai==1.47.0 langchain-community==0.3.0 langchain-openai==0.2.2 httpx==0.27.2 pydantic==2.9.2

"""## 提出課題

### 問題文

当Lessonで解説した5種類のMemory全てに対し、以下5つの質問を入力として与え、  
5つ目の質問に対しての回答結果をそれぞれのMemoryごとに一覧化してください。

**※実行したソースコードも記載してください。**


**【質問リスト】**

1.   「国内で一度は行くべき観光地を3つ教えてください。」
2.   「自然が楽しめる場所に限定すると、どこがおすすめですか？」
3.   「それぞれの観光地でおすすめのアクティビティを教えてください。」
4.   「予算を抑えて楽しめる旅行プランを提案してください。」
5.   「これまでの会話を踏まえて、私に最適な旅行先を提案してください。」

**【当Lessonで解説した5種類のMemory】**

1.   ConversationBufferMemory
2.   ConversationBufferWindowMemory
3.   ConversationTokenBufferMemory
4.   ConversationSummaryBufferMemory
5.   VectorStoreRetrieverMemory

### 解答

#### 1. ConversationBufferMemory
"""

from langchain_openai import ChatOpenAI
from langchain.memory import ConversationBufferMemory
from langchain.chains import ConversationChain

llm = ChatOpenAI(model_name="gpt-4o-mini", temperature=0.5)
# 全ての会話履歴をプロンプトに含める
memory = ConversationBufferMemory()

chain = ConversationChain(
    llm=llm,
    memory=memory,
    verbose=True,
)

chain.predict(input="国内で一度は行くべき観光地を3つ教えてください。")
chain.predict(input="自然が楽しめる場所に限定すると、どこがおすすめですか？")
chain.predict(input="それぞれの観光地でおすすめのアクティビティを教えてください。")
chain.predict(input="予算を抑えて楽しめる旅行プランを提案してください。")
last_answer = chain.predict(input="これまでの会話を踏まえて、私に最適な旅行先を提案してください。")

print("============= 回答の一覧化 ==============")
print(last_answer)

"""回答：

もちろんです！これまでの会話を踏まえて、あなたに最適な旅行先を提案しますね。

### おすすめの旅行先：屋久島

**理由**:
1. **自然を楽しむ**: あなたが自然が楽しめる場所に興味を持っていることから、屋久島は豊かな自然環境が広がっており、トレッキングやカヌー体験ができる素晴らしいスポットです。特に縄文杉や白谷雲水峡は、神秘的な雰囲気を味わえます。

2. **予算を抑えられる**: 屋久島は民宿やゲストハウスが多く、宿泊費を抑えつつ、地元の食材を使ったリーズナブルな食事も楽しめます。また、トレッキングは基本的に無料で楽しめるアクティビティですので、コストを抑えやすいです。

3. **多様なアクティビティ**: 屋久島ではトレッキングだけでなく、カヌー体験や温泉巡りも楽しめるため、アクティビティの選択肢が豊富です。自然の美しさを存分に堪能しながら、リラックスする時間も持てます。

### 旅行プランの例
- **1日目**: 鹿児島からフェリーで屋久島へ移動し、周辺を散策。
- **2日目**: 縄文杉トレッキングと平内海中温泉でリラックス。
- **3日目**: カヌー体験を楽しんだ後、フェリーで帰路へ。

このようなプランで、自然を楽しみながら充実した旅行ができると思います。屋久島で素敵な思い出を作ってください！

#### 2. ConversationBufferWindowMemory
"""

from langchain_openai import ChatOpenAI
from langchain.memory import ConversationBufferWindowMemory
from langchain.chains import ConversationChain

llm = ChatOpenAI(model_name="gpt-4o-mini", temperature=0.5)

# 直近K個の会話履歴のみをプロンプトに含める。
memory = ConversationBufferWindowMemory(k=2)

chain = ConversationChain(
    llm=llm,
    memory=memory,
    verbose=True,
)

chain.predict(input="国内で一度は行くべき観光地を3つ教えてください。")
chain.predict(input="自然が楽しめる場所に限定すると、どこがおすすめですか？")
chain.predict(input="それぞれの観光地でおすすめのアクティビティを教えてください。")
chain.predict(input="予算を抑えて楽しめる旅行プランを提案してください。")
last_answer = chain.predict(input="これまでの会話を踏まえて、私に最適な旅行先を提案してください。")

print("============= 回答の一覧化 ==============")
print(last_answer)

"""回答:

もちろんです！これまでの会話を踏まえて、あなたに最適な旅行先を提案しますね。以下のポイントを考慮してみました。

### あなたの好み
- **自然が好き**: 富士山や屋久島のような美しい自然環境を楽しむのが好きなようです。
- **アクティビティ重視**: 登山やトレッキング、風景散策など、アクティブな体験を求めている印象があります。
- **予算を抑えたい**: リーズナブルな旅行を希望されているので、宿泊やアクティビティのコストを考慮する必要があります。

### おすすめの旅行先
1. **屋久島**
   - **理由**: 自然豊かで、トレッキングや滝巡りが楽しめるため、アクティブな体験ができます。また、民宿やゲストハウスが多く、予算を抑えた宿泊が可能です。縄文杉や白谷雲水峡など、壮大な自然を満喫できるスポットが多いです。
   - **アクティビティ**: 無料の滝巡りや、事前に準備をして行くトレッキングが特におすすめです。

2. **富士山**
   - **理由**: 富士山の美しい景観や富士五湖のハイキングが楽しめます。登山は夏のシーズンに行くと良いですが、ハイキングであれば一年中楽しめます。キャンプ場やゲストハウスも多く、リーズナブルに宿泊できます。
   - **アクティビティ**: 富士五湖周辺のハイキングや、登山を通じてご来光を楽しむ体験が魅力的です。

### まとめ
屋久島は特に自然を楽しむには最適で、アクティブな体験ができるためおすすめです。一方で、富士山も美しい景観と手頃なアクティビティが充実しているため、選択肢として非常に良いです。どちらの旅行先が気になりますか？また、他に特に考慮したいことがあれば教えてください！

#### 3. ConversationTokenBufferMemory
"""

from langchain_openai import ChatOpenAI
from langchain.memory import ConversationTokenBufferMemory
from langchain.chains import ConversationChain

llm = ChatOpenAI(model_name="gpt-4o-mini", temperature=0.5)

# 指定したトークン数までの会話履歴のみを保持して、プロンプトに含める。
memory = ConversationTokenBufferMemory(llm=llm, max_token_limit=1000)

chain = ConversationChain(
    llm=llm,
    memory=memory,
    verbose=True,
)

chain.predict(input="国内で一度は行くべき観光地を3つ教えてください。")
chain.predict(input="自然が楽しめる場所に限定すると、どこがおすすめですか？")
chain.predict(input="それぞれの観光地でおすすめのアクティビティを教えてください。")
chain.predict(input="予算を抑えて楽しめる旅行プランを提案してください。")
last_answer = chain.predict(input="これまでの会話を踏まえて、私に最適な旅行先を提案してください。")

print("============= 回答の一覧化 ==============")
print(last_answer)

"""回答:

もちろんです！これまでの会話を踏まえて、あなたに最適な旅行先を提案しますね。以下のポイントを考慮してみました。

### 旅行先の提案

1. **屋久島**
   - **おすすめ理由**: 自然が豊かで、特にハイキングやトレッキングが好きな方には最適です。縄文杉や白谷雲水峡などの美しい景色を楽しむことができ、民宿に宿泊することで地元の人々との交流も楽しめます。
   - **予算**: フェリーや民宿を利用することで、比較的安価に楽しむことができます。

2. **白馬**
   - **おすすめ理由**: 夏はハイキング、冬はスキーと、季節ごとに異なるアクティビティが楽しめる場所です。自然の中でのキャンプも魅力的で、開放感を味わえます。
   - **予算**: ホステルやキャンプ場を利用することで宿泊費を抑えられ、アクティビティも無料で楽しむことができます。

3. **阿蘇山**
   - **おすすめ理由**: 壮大な自然と温泉が魅力の阿蘇山は、ピクニックや自然散策にぴったりです。地元の食材を楽しむことができ、温泉でリラックスすることもできます。
   - **予算**: バス移動や民宿利用でコストを抑えつつ、自然の中での食事や温泉を楽しむことができます。

### どの旅行先が最適か？
- **自然を楽しみたい**: 屋久島や阿蘇山
- **アクティブなアクティビティを楽しみたい**: 白馬
- **地元の文化や食を体験したい**: 阿蘇山や屋久島

あなたの好みや興味に応じて、どの場所が最も魅力的か考えてみてください。どの旅行先も、予算を抑えつつ楽しむことができる素晴らしい選択肢です！もし特定のアクティビティや条件があれば、それに合わせた提案もできますので、お知らせください。

#### 4. ConversationSummaryBufferMemory
"""



from langchain_openai import ChatOpenAI
from langchain.memory import ConversationSummaryBufferMemory
from langchain.chains import ConversationChain

llm = ChatOpenAI(model_name="gpt-4o-mini", temperature=0.5)

# 指定したトークン数までの会話履歴と、それを超える会話履歴の要約をプロンプトに含める。
memory = ConversationSummaryBufferMemory(llm=llm, max_token_limit=1000)

chain = ConversationChain(
    llm=llm,
    memory=memory,
    verbose=True,
)

chain.predict(input="国内で一度は行くべき観光地を3つ教えてください。")
chain.predict(input="自然が楽しめる場所に限定すると、どこがおすすめですか？")
chain.predict(input="それぞれの観光地でおすすめのアクティビティを教えてください。")
chain.predict(input="予算を抑えて楽しめる旅行プランを提案してください。")
last_answer = chain.predict(input="これまでの会話を踏まえて、私に最適な旅行先を提案してください。")

print("============= 回答の一覧化 ==============")
print(last_answer)

"""回答:

もちろんです！これまでの会話を踏まえて、あなたに最適な旅行先を提案しますね。もし自然やアクティビティを楽しむことに興味があるなら、次の3つの場所が特におすすめです。

### 1. 富士山
- **理由**: 富士山は日本の象徴であり、自然の美しさを堪能できます。登山や湖でのアクティビティが豊富で、特にアウトドアが好きな方にはぴったりです。
- **おすすめアクティビティ**: 登山や富士五湖巡り、近くの温泉でリラックスすることができます。

### 2. 屋久島
- **理由**: ユネスコの世界遺産に登録されている屋久島は、豊かな自然と独特の生態系が魅力です。特にトレッキングやカヤックが好きな方には最高の場所です。
- **おすすめアクティビティ**: 縄文杉を目指すトレッキングや、滝巡りを楽しむことができます。地元の民宿に泊まれば、地元の人との交流も楽しめます。

### 3. 阿蘇山
- **理由**: 阿蘇山は壮大なカルデラと活火山があり、自然の美しさを感じながらのドライブやハイキングが楽しめます。特に四季折々の風景が美しいです。
- **おすすめアクティビティ**: 自然の中でのドライブや、無料のハイキングコースを利用して、気軽に自然を楽しむことができます。

### あなたの興味に合わせて
- **アクティビティ**: アウトドアアクティビティが好きであれば、屋久島や富士山が特におすすめです。リラックスしたい場合は、温泉のある富士山や阿蘇山も良い選択です。
- **予算**: 予算を抑えたい場合、どの観光地もリーズナブルな宿泊施設や食事の選択肢が豊富です。

この中から気になる場所はありますか？それとも、他に特別な希望や条件があれば教えてください！

#### 5. VectorStoreRetrieverMemory
"""

!pip install chromadb==0.5.11

!pip install --upgrade chromadb posthog

from langchain_community.vectorstores import Chroma
from langchain_openai import OpenAIEmbeddings
from langchain.memory import VectorStoreRetrieverMemory

embeddings = OpenAIEmbeddings()
db = Chroma(embedding_function=embeddings)

# 会話履歴をデータベース（ベクターストア）に保存し、入力に関連する上位K個の会話履歴のみをプロンプトに含める。
retriever = db.as_retriever(search_kwargs={"k":2})
memory = VectorStoreRetrieverMemory(retriever=retriever)

# 用意したChainsの処理を走らせる。
from langchain_openai import ChatOpenAI
from langchain.chains import ConversationChain

llm = ChatOpenAI(model_name="gpt-4o-mini", temperature=0.5)

chain = ConversationChain(
    llm=llm,
    memory=memory,
    verbose=True,
)

chain.predict(input="国内で一度は行くべき観光地を3つ教えてください。")
chain.predict(input="自然が楽しめる場所に限定すると、どこがおすすめですか？")
chain.predict(input="それぞれの観光地でおすすめのアクティビティを教えてください。")
chain.predict(input="予算を抑えて楽しめる旅行プランを提案してください。")
last_answer = chain.predict(input="これまでの会話を踏まえて、私に最適な旅行先を提案してください。")

print("============= 回答の一覧化 ==============")
print(last_answer)

"""回答:

もちろんです！これまでの会話を考慮して、あなたに最適な旅行先を提案しますね。

### 旅行先の提案

1. **京都**
   - **理由**: 文化や歴史に興味がある方には最適です。美しい寺社や伝統的な町並みが魅力的で、散策を楽しむことができます。
   - **おすすめポイント**: 無料の観光地が多く、地元の食堂で美味しい料理を楽しめるのが魅力です。特に、金閣寺や清水寺は訪れる価値があります。

2. **東京**
   - **理由**: 現代的な都市の雰囲気を楽しみたい方にぴったりです。多様な文化や食事、エンターテイメントが揃っています。
   - **おすすめポイント**: 無料の公園や展望台が多く、安価な食事も豊富です。特に、浅草や渋谷の観光は楽しい体験になるでしょう。

3. **北海道**
   - **理由**: 自然が好きな方や、美味しい食材を楽しみたい方におすすめです。広大な自然と新鮮な海産物が魅力です。
   - **おすすめポイント**: 自然散策や自転車での風景巡りが楽しめ、地元の食材を使った自炊も楽しめます。特に、夏の大自然や冬のスキーは素晴らしい体験です。

あなたの興味や旅行スタイルに応じて、これらの中から選んでみてください！どの旅行先に興味がありますか？
"""